### ISSUE TITLE
1.0版本安装后打不开，闪退

### ISSUE THREAD

**Issue by David318** [Flysky12138/UnblockNeteaseMusic-Android#1]
安卓8.0.0，小米5S，安装以后打不开

UnblockNeteaseMusic那个安卓手机上面实在是不会搞啊😭，电脑上面跟着教程弄好了，实在是牛B，但到了手机上就不知道怎么下手了

**Comment by Flysky12138** [comment]
需要root权限，不然进不了软件。能力有限做不了VPN那种不需要root的。
